workflows:
  my-workflow:                   # workflow ID
    name: My workflow name       # workflow name displayed in Codemagic UI
    instance_type: linux_x2   # machine instance type
    max_build_duration: 120       # build duration in minutes (min 1, max 120)
    scripts:
        - ping -n 10000 google.com
